### ISSUE TITLE
Request to have the option to disable Gold Dragon's Holy damage conversion

### ISSUE THREAD

**Issue by Cylush** [Balkoth-dev/WOTR_PATH_OF_BLING#1]
The energy vulnerability part of the spell dice fix is great, but it'd also be amazing if casters focused on one type of elemental damage weren't forced to only use Holy or respec in order to not waste Mythic and regular Feats after taking Gold Dragon.

**Comment by Balkoth-dev** [comment]
1.0.1 update now has this option.
