### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Seinra** [Balkoth-dev/WOTR_PATH_OF_BLING#2]
Hello! Thanks for the mod, I'm loving it.
I want to ask if it is possible for you to make the Alchemist's spellbook be mergeable with your spellbook for the Gold Dragon? And with the druid spellbook too if possible (I don't know if it is mergeable already). I ask this because I would like to have the metamorph classes spellbooks be mergeable with the Golden Dragon spellbook. Sorry for my bad english.

**Comment by Balkoth-dev** [comment]
Hello Lukas, thank you for making an issue for this. 

You can merge the spellbook using Toybox's features, however you will lose out on certain spell levels from the dragon's spellbook with Alchemist. Editing the alchemist spellbook itself to allow 7-9 level spells could cause problems outside of the scope of the mod. 

Thank you for understanding.
