### ISSUE TITLE
Spellbook Merge

### ISSUE THREAD

**Issue by Axel-of-the-Key** [Balkoth-dev/WOTR_PATH_OF_BLING#5]
I have no idea if such a thing is even possible, but since you added a spellbook I was curioius if spellbook merging could possibly be enabled. I was chugging along with my planned playthrough of Azata->Gold Dragon and I am sad to lose my spellbook merge. If I could at least respec into a class that made sense to merge spellbooks, that would be cool. I see that you added a spellbook for them in the first place so I'm curious if merging could be added (along the lines of the mod that adds more classes to the existing merges).

**Comment by Balkoth-dev** [comment]
Hey there. There are no plans at this time to make the new spellbook work with spellbook merging.
